### ISSUE TITLE
In safari it isn't working. Tested on ios and os x.

### ISSUE THREAD

**Issue by sebabromberg** [westonsoftware/vue-webrtc#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by westonsoftware** [comment]
See [this ](https://caniuse.com/#feat=stream) for browser compatibility, I'm not able to try it.  I'll accept a PR if you get this working.  Thanks
--Andy
