### ISSUE TITLE
how record video and audio to media file and save it in storage

### ISSUE THREAD

**Issue by AhmadAlaswadDev** [westonsoftware/vue-webrtc#103]
how can I record video and audio for all peers and save it as mp4 file to upload it to cloud service such as GCP or AWS

**Comment by AhmadAlaswadDev** [comment]
thank you for answering but how can integrate it with vue-webrtc ?

is there native way to get the buffer for specific channel or user using vue-webrtc  ?
so i can save it as mp4 file and upload it to cloud service

**Comment by westonsoftware** [comment]
You might try something like this ... https://github.com/muaz-khan/RecordRTC
But you will be limited by memory and only to a single stream on the client side.
