### ISSUE TITLE
width adjusting doesn't work

### ISSUE THREAD

**Issue by mykola-zomchak** [westonsoftware/vue-webrtc#12]
**Describe the bug**
Width of component does not adjust using attributes or styles.

**To Reproduce**
Set 'width' attribute to '100%'

**Expected behavior**
width of video component is changed

**Screenshots**
![image](https://user-images.githubusercontent.com/39236497/80242210-ac63cb80-866d-11ea-9300-54b0ed9bf7bd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81

**Comment by westonsoftware** [comment]
Hi, try adjusting the height.  The control is a list of videos that extends to the right.
