### ISSUE TITLE
Server error? cannot connect to peer

### ISSUE THREAD

**Issue by bestian** [westonsoftware/vue-webrtc#121]
**Describe the bug**
I'm using the demo site:
https://westonsoftware.github.io/vue-webrtc/

but when I joined with two different divice into same room in same time, both can't see the other

**To Reproduce**
1. Go to ['DEMO'](https://westonsoftware.github.io/vue-webrtc/) with two different divice into same room in same time
2. Click on 'JOIN'
3. See error

**Expected behavior**
They shoud see each other

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.0.1
 - Browser chrome
 - Version    108.0.5359.124

**Smartphone (please complete the following information):**
 - Device: iphone 8
 - OS: iOS 16.2
 - Browser: safari

**Comment by bestian** [comment]
console logged: Error connecting to peer

**Comment by westonsoftware** [comment]
Hi, for WebRTC connection issues like this you can run on the same network, or setup STUN and TURN servers.

**Comment by bestian** [comment]
thank you
