### ISSUE TITLE
turn on video after joined room with video off

### ISSUE THREAD

**Issue by thobiasvicente** [westonsoftware/vue-webrtc#127]
When i enter the room with the param enableVideo = false, and need to active video, nothing happens.

Also i can do the opposite, when i enter the room with enableVideo = true, i can turn off by accessing the DOM  stream and disable/enable the track. But i like to enter the room with video off.

**Comment by westonsoftware** [comment]
Hmm, after you change the setting, try calling .leave() and .join().
