### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by adrianoGaspar** [westonsoftware/vue-webrtc#13]
Hello, I'm starting with vue. Could you please provide a more detailed example of how to get started?
I did the installation, put the component but nothing appears on the screen.

**Comment by westonsoftware** [comment]
Hi, will you need to create your own vue.js "hello world" project with it's own project.json file first.  You can then use "npm install vue-webrtc " there.  See getting started either with the Vue CLI or (my favorite) the Quasar Framework to setup your own build.
--Andy
