### ISSUE TITLE
I can't use WebRTC!

### ISSUE THREAD

**Issue by javokhirbekkhaydarov** [westonsoftware/vue-webrtc#130]
![image](https://github.com/westonsoftware/vue-webrtc/assets/79502483/12944982-695b-4fad-81ce-579e4bb846f4) 
<h1> 

Now I'm using vue3  </h1>

![image](https://github.com/westonsoftware/vue-webrtc/assets/79502483/f327522b-f570-479b-be31-99e2487a69ae)

<h3> I wanted to use WebRTC and installed version 3.0.1. but it doesn't fit my project. what could be the error </h3>

**Comment by westonsoftware** [comment]
Hmmm ... try building this sample which is Vue 3 ... https://github.com/westonsoftware/vue-webrtc/blob/master/sample/package.json

Then compare your project to that to get it working.

**Comment by javokhirbekkhaydarov** [comment]
> Hmmm ... try building this sample which is Vue 3 ... https://github.com/westonsoftware/vue-webrtc/blob/master/sample/package.json
> 
> Then compare your project to that to get it working.

<h3> Hi bro.
here my vue version =>      "vue": "^3.2.45",  </h3>

my project is almost finished now i want to use webRTC to organize webinars.
I installed the webRTC package in my project few days ago but it showed several errors.
I installed all these versions but it shows error.


3.0.1 Added ioOptions for Socket IO
3.0.0 Migrated from Vue 2 to Vue 3
2.0.0 Replaced signaling server and webrtc library with SimplePeer

**Comment by javokhirbekkhaydarov** [comment]
<h1>  Hi bro I install vue 3 and vue webrtc  but show this error</h1>
here my packgage json

![image](https://github.com/westonsoftware/vue-webrtc/assets/79502483/e3f2a4c6-cef5-42c3-aeca-4f2b452a49de)

<h3> and here bug</h3>

![image](https://github.com/westonsoftware/vue-webrtc/assets/79502483/8720e37f-115b-4988-9256-acbc697f26c2)

what is this error please look packgage

**Comment by westonsoftware** [comment]
Hey, no sure, node-gyp errors are usually a node version mis-match?  Should core-js really be there?
Again, try to match this sample package file ... https://github.com/westonsoftware/vue-webrtc/blob/master/sample/package.json
