### ISSUE TITLE
Steps to move from localhost to https://www.something.com

### ISSUE THREAD

**Issue by lhcdims** [westonsoftware/vue-webrtc#15]
Hi All,

If anyone tried the demo using https instead of localhost, please kindly write down the procedures for the others, thank you.

This is what I've done in my ubuntu 18.04:

1. Go to Home directory
```
cd ~
```

2. Create a directory called 'vue'
```
mkdir vue
cd vue
```

3. Clone the vue-webrtc project
```
git clone https://github.com/westonsoftware/vue-webrtc.git
```

4. change the name of the directory
```
mv vue-webrtc vue-webrtc_proj
cd vue-webrtc_proj
```

5. modify the name of the project in package.json, from vue-webrtc to vue-webrtc_proj
Use gedit or other text editor:
```
gedit package.json
```

Then replace the second line with the line below:
```
  "name": "vue-webrtc_proj",
```

6. Install the vue-webrtc: (You can't install vue-webrtc if you don't rename your project directory)
```
npm install vue-webrtc --save
```

7. Build the Demo
```
npm run-script builddemo
```

8. Run the Demo
```
npm run-script demo
```

Then a browser will be opened automatically, the url is http://localhost:8080 and the demo page will be shown.

And my problem is, say I have a domain name, e.g. www.abc.com, and already got certificates from letsencrypt, what should I do in order to run the demo using url:

https://www.abc.com

Thank you.

**Comment by westonsoftware** [comment]
Hi, you need to create your own vue.js "hello world" project with it's own project.json file.  You can then use "npm install vue-webrtc " there.  See either the Vue CLI or (my favorite) the Quasar Framework to setup your own build.

To deploy your project to abc.com, you can use a service like Netlify.com to publish your build files and your cert.
--Andy
