### ISSUE TITLE
Code examples

### ISSUE THREAD

**Issue by githubber-cyber** [westonsoftware/vue-webrtc#17]
Hi there! Would you be able to provide a few code examples? Also, would you interested in collaborating for a startup? We are building something pretty cool! Thanks!

**Comment by westonsoftware** [comment]
Hi, I added a Vue CLI sample in the ./sample folder just last week.  Also, the demo src uses almost all of the features.  Contact me on LinkedIn if you want to talk more.

**Comment by githubber-cyber** [comment]
Great! Not big on LinkedIn, but can can talk via Skype! nyconn@gmail.com (Please delete this (email) after reading, thank you.)
