### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gathuku** [westonsoftware/vue-webrtc#18]
Hi @westonsoftware  please help, tried using the package with laravel and vue. Seems the component is registered but nothing appears

![Screenshot from 2020-05-31 14 31 42](https://user-images.githubusercontent.com/26896865/83351374-e8b0d880-a34b-11ea-9bbf-d7bb0989f463.png)

**Comment by westonsoftware** [comment]
Hi gathuku, I just created a chat channel where you can get help:  https://gitter.im/westonsoftware/vue-webrtc
--Andy

**Comment by mastashake08** [comment]
I joined your chat and asked a question. I followed th window.io fix and called join. Still see nothing
