### ISSUE TITLE
Template not displaying

### ISSUE THREAD

**Issue by EaseOnConsole** [westonsoftware/vue-webrtc#19]
Hi i have installed library in vue js. Its installed successfully. I have added the code of template.
<vue-webrtc width="100%" roomId="roomId">
</vue-webrtc>

But nothing is displayed on page and also no error. Kindly help me I have followed all steps,installed library,added in template like explained but page is not showing any thing

**Comment by westonsoftware** [comment]
Hi there is no style by default, you'll need to call .join() to see your video start.  
See /samples/src/App.vue or /demo/src
