### ISSUE TITLE
Does it need to be in the same network...?

### ISSUE THREAD

**Issue by JayCasee** [westonsoftware/vue-webrtc#25]
Thank you for your great code sharing, and I have a short question.
As I've tested the demo, it is working with the devices on the same network.
To make it to connect devices in efferent networks, what should I do more...?
Thank you very much for reading my question.

---- ---- ---- ----

Just right after my question, I've slightly realized STUN, TURN, ICE & Signalling.
So, it seems I need to use TURN servers for the NAT issue.
BTW, what if there is already set TRUN server, how can I connect the server to my code...?

**Comment by westonsoftware** [comment]
Hi, yes, that is right, issue #6 is in the queue to add this option.  I'll try to do this next.
