### ISSUE TITLE
How to ban (make a specific user to leave from the room) a user...?

### ISSUE THREAD

**Issue by JayCasee** [westonsoftware/vue-webrtc#28]
First of all, I always appreciate for your great works.

I have a question that...

**Is there any method which makes a user (not me) to leave from the connection...?**

Something like...

```
this.$refs.webrtc.leave( [ videoList.key ] )
```

I've tried to analyse this.$refs.webrtc, but I couldn't find the way.

**Comment by westonsoftware** [comment]
There are no methods to manage users here.  
I would look at this API ... https://www.rtcmulticonnection.org/docs to add that functionality.

**Comment by JayCasee** [comment]
Thank you for your response, and I'm leaving a memo for someone like me in the future.

I've just realized `this.$refs.webrtc` includes `rtcmConnection` object.

So, I've made "ban" as below.

```
this.$refs.webrtc.rtcmConnection.disconnectWith( this.$refs.webrtc.rtcmConnection.getAllParticipants()[ 0 ] )
```
In the above, "0" means the index of the user. E.g. myself has no index, first comer has index as 0.
