### ISSUE TITLE
Chrome loading 

### ISSUE THREAD

**Issue by RezaErfani67** [westonsoftware/vue-webrtc#32]
**Describe the bug**
Chrome not load second connection

**To Reproduce**
1. Join to public room
2. Then join with another mobile on the same channel

**Expected behavior**
It should shows 2 camera but show the first

**Screenshots**

**Desktop (please complete the following information):**
 
Working good
**Smartphone (please complete the following information):**
 - Device: [samsung]
 - OS: [android]
 - Browser [chrome ]
 - Version 83.0.4

**Comment by westonsoftware** [comment]
The mobile should be on the same network, or add a TURN server.

**Comment by RezaErfani67** [comment]
I  use your demo for test...
your demo link works good on chrome on desktop  but not work with mobile

**Comment by RezaErfani67** [comment]
could you please give me a sample with version 2 of vue-webrtc ?

**Comment by westonsoftware** [comment]
> could you please give me a sample with version 2 of vue-webrtc ?
> how can i add TURN option to config?

git checkout tags/v1.2.1

set the turnServer property
