### ISSUE TITLE
I can't get it to work on my project

### ISSUE THREAD

**Issue by lokize** [westonsoftware/vue-webrtc#37]
First, thanks for the nice work i installed npm and imported all this code in main.js

```
import Vue from 'vue'
import WebRTC from 'vue-webrtc'
Vue.use(WebRTC)

and inserted  
<vue-webrtc width="100%" roomId="roomId">
</vue-webrtc> in my page
```

but nothing happens, do not load the plugin

**Comment by chovy** [comment]
are you getting any errors in the console?

**Comment by lokize** [comment]
no, no errors in console, besides the steps I mentioned above do I need to do anything else for the plugin to work on my project?

**Comment by rahmedd** [comment]
I'm had the same issue when running the sample as well. The socket.io-client package was recently updated to v3.0.0 and this may be causing the issue. Downgrade the socket.io-client package to version 2.3.1.

**Comment by westonsoftware** [comment]
I just bumped the /sample project up to 1.2.2 and it seems to work fine.
@lokize make sure that you are calling .join() in your code the way that /sample/src/App.vue is doing it

**Comment by kirschkern** [comment]
> I'm had the same issue when running the sample as well. The socket.io-client package was recently updated to v3.0.0 and this may be causing the issue. Downgrade the socket.io-client package to version 2.3.1.

Thanks @rahmedd! Downgrading socket.io-client to 2.3.1 fixed it for me. After restarting the server I see the video. Hooray!
Would be great to see this working with the latest version as well.
