### ISSUE TITLE
Sample only works on localhost, not on "my-local-ip"

### ISSUE THREAD

**Issue by mpena2099** [westonsoftware/vue-webrtc#42]
Hi!

Steps:
$ git clone https://github.com/westonsoftware/vue-webrtc
$ cd vue-webrtc/sample/
$ yarn install
$ yarn serve

http://localhost:8080/    -> shows webcam image 

http://192.168.0.43:8080/ -> **only shows the Vue logo and, on webconsole**: "_Uncaught TypeError: navigator.getUserMedia is not a function_"

Thanks!
Mauricio

**Comment by westonsoftware** [comment]
Try https and see if that works

**Comment by mpena2099** [comment]
> Try https and see if that works

No effect. I see "ERR_SSL_PROTOCOL_ERROR" on browser.

But as seen in https://forum.vuejs.org/t/vue-cli-serve-with-https/39359/4, I created this file below in /sample directory and now it worked! It even allowed the selection of camera and microphone.

vue.config.js
```
module.exports = {
  devServer: {
    https: true
  }
}
```

![Captura de tela de 2021-01-27 16-11-43](https://user-images.githubusercontent.com/1200886/106041977-3ccab300-60bb-11eb-9df5-061b8a60e26d.png)

**Comment by mpena2099** [comment]
Just `$ yarn serve --https ` works too.
