### ISSUE TITLE
error "io" is not defined 

### ISSUE THREAD

**Issue by westonsoftware** [westonsoftware/vue-webrtc#5]
This dependency issue is causing compile errors ...
[https://github.com/muaz-khan/RTCMultiConnection/issues/620 ](https://github.com/muaz-khan/RTCMultiConnection/issues/620 )

As a workaround, try adding this until we get it fixed:

import * as io from 'socket.io-client'
window.io = io

**Comment by sebabromberg** [comment]
Hi! This error still remains. Do you have planes to fix it? Do you need help?
Thaks for this library!

**Comment by westonsoftware** [comment]
> Hi! This error still remains. Do you have planes to fix it? Do you need help?
> Thaks for this library!

I was hoping that RTCMultiConnection would fix the issue there that we could then update to here but I haven't seen it yet.  PR's are welcome if you know another way.

**Comment by RacerDelux** [comment]
Just curious if this has been addressed yet?

**Comment by westonsoftware** [comment]
No, just checked, they have 600 issues over there now, your best bet would be to do a PR for them.  Or just add these two lines here.

**Comment by westonsoftware** [comment]
Fixed in V2.
