### ISSUE TITLE
can't join room, joined-room event not firing

### ISSUE THREAD

**Issue by jrobertdahl** [westonsoftware/vue-webrtc#51]
My apologies if I'm just missing something here, but when I set up the Vue project you outline on the project's github page, I am unable to join a room and the joined-room event does not fire. I am not seeing any console errors coming from the join method. I've even copied and pasted in the code from your [demo page](https://westonsoftware.github.io/vue-webrtc/) (which does work) and it still isn't working. 

I first noticed the issue while going through this [LinkedIn Learning course](https://www.linkedin.com/learning/building-a-video-chat-app-with-vue-js-and-firebase), which includes your vue-webrtc component. If I pull down webrtc's [demos](https://webrtc.github.io/samples/), I can run them just fine. 

You can see a live, unstyled version of the demo I've recreated [here](https://vue-webrtc-component-sample.web.app/). I've dug through the component code a bit but I'm not familiar with a lot of this functionality, so I thought I'd leave it to the pros! Thanks!

Mac OS 11.2.3
Chrome v90/Safari 14

**Comment by MaximeFth** [comment]
Hi, I have the exact same problem here, been stuck on it a while :(

**Comment by MaximeFth** [comment]
Try downgrading your socket.io-client version to 2.3.1, worked for me

**Comment by muarachmann** [comment]
@westonsoftware I noticed that this doesn't work with the latest version of `socket.io-client` downgrading does the trick. Is there any ETA on it to support the latest version?

**Comment by westonsoftware** [comment]
Hi @muarachmann, the thing is that my component doesn't even use socket.io, this is a dependency that is pulled in by the RTCMultiConnection library.  I have plans to completely replace that lib for V2 because it is outdated but I don't have an ETA on that.  Maybe this summer.  --Andy

**Comment by muarachmann** [comment]
@westonsoftware thanks for your reply. I noticed this too when looking at the source code. I would love to contribute should you plan on an upgrade. BR

**Comment by westonsoftware** [comment]
Fixed in V2.
