### ISSUE TITLE
Allow the component to use STUN and TURN servers.

### ISSUE THREAD

**Issue by westonsoftware** [westonsoftware/vue-webrtc#6]
Propose adding an options property that matches the underlying RTCMultiConnection settings.
[https://www.rtcmulticonnection.org/docs/iceServers/](https://www.rtcmulticonnection.org/docs/iceServers/)

**Comment by JohnYii** [comment]
Did this happen? Or it is on the todo list?

**Comment by westonsoftware** [comment]
Still open, the idea would be to start exposing some of these settings as properties:
https://github.com/muaz-khan/RTCMultiConnection/blob/master/docs/api.md
Open to ideas.

**Comment by JayCasee** [comment]
I'm sorry for my questions are many.

FYI, I've updated this to 1.2.2, and I've set stunServer & turnServer properties with some free providers, but it seems nothing changed.

**Do you have any recommendation about STUN and TURN server providers...?**

Although they may be paid (not free) providers, it will be very helpful to test.

Thank you.

**Comment by westonsoftware** [comment]
You can test your servers on this site ... 
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
Here is a docker file for running your own coturn server ...
https://github.com/instrumentisto/coturn-docker-image
