### ISSUE TITLE
index.js:9493 Uncaught (in promise) DOMException: Requested device not found

### ISSUE THREAD

**Issue by zzx131** [westonsoftware/vue-webrtc#66]
when i click "join" not work and the following error message appears in the picture, help me, thank you .
![devicenotfound](https://user-images.githubusercontent.com/22722085/121174730-cf126d00-c88c-11eb-884f-c384d0fb8d0b.png)

**Comment by westonsoftware** [comment]
Is your deviceId correct?  set it to null or set enableVideo = false if you don't want it.
look at getUserMedia() for more info.
