### ISSUE TITLE
Limit Video chat to one Broadcaster

### ISSUE THREAD

**Issue by muarachmann** [westonsoftware/vue-webrtc#68]
**Is your feature request related to a problem? Please describe.**
Hi @westonsoftware plus one on this package and I am so much liking it. I have this feature which I want only one user to be able to broadcast and the others join in but their cameras are not turned on. I wish to have a one on many video chat like say one host and many users connecting to it say to listen the host show. I wish to know how to go about this feature thanks

**Describe the solution you'd like**

**Describe alternatives you've considered**
I tried destroying the divs of streams created by the for loop but this doesn't solve the issue as the Camera of other users are still on

**Additional context**

**Comment by muarachmann** [comment]
Another option is to hide the divs display but anyone can toggle this to display block upon inspecting the element since the camera is on

**Comment by westonsoftware** [comment]
hi @muarachmann, you could set enableVideo = true for the broadcaster and false for the listeners when they connect.  However, I think you still need either audio or video for the connection to work.  Remember, peer to peer supports a limited number of users too so you wouldn't be able to broadcast to a large number of people like I think you want.

**Comment by muarachmann** [comment]
@westonsoftware thanks for your response. I will be needing only audio for the other listeners and video for the "host". Also you seem to be correct about my usecase. Any recommendations on what to use to accomodate a larger audience say 1k-2k users simultaneously? thanks

**Comment by westonsoftware** [comment]
that is usually done by converting the video to MPEG-DASH or HLS using streaming server like Wowza
