### ISSUE TITLE
TURN server error

### ISSUE THREAD

**Issue by RezaErfani67** [westonsoftware/vue-webrtc#73]
**Describe the bug**

i have TURN server but it does not work ...
every one just only see him/her self...
[DEMO ](https://doctorjs.ir/video)is here

error while second person join to room...
![image](https://user-images.githubusercontent.com/24381986/132135027-11687006-f001-45b7-9b0c-675590340c7f.png)

**To Reproduce**
if 3 person exists in the room, i should see 3 video stream...

**Screenshots**
![image](https://user-images.githubusercontent.com/24381986/132083178-70eb2f81-3d02-49d1-a337-fb2a1c37d38f.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser Chrome
 - Version 92

**Smartphone (please complete the following information):**
 - Device: IPHONE11
 - OS: IOS 14.6
 - Browser Chrome

**Comment by bipinparmar-ss** [comment]
I got the same error. I have installed in my project and for some user, it's working fine and for some user, it's not working and giving "ERR_CONNECTION_TIMEOUT" even if they have same browser version.

![Screenshot 2021-09-06 133018 (2)](https://user-images.githubusercontent.com/77672651/132184597-13e9d637-12c7-4784-a7a7-0e8d6a0e5c90.png)

**Comment by westonsoftware** [comment]
Try to verify your turn server here to see if it is ok ...
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

**Comment by RezaErfani67** [comment]
my problem related to TURN server...
i used to https://xirsys.com and every think was OK...
