### ISSUE TITLE
add option for io

### ISSUE THREAD

**Issue by RezaErfani67** [westonsoftware/vue-webrtc#74]
could you add custome options for io like {path:'/subdir/socket.io'} and etc

```javascript
this.socket = io(this.socketURL, { -------custome options------- });
```

**Comment by westonsoftware** [comment]
Yes, the default options are ... { rejectUnauthorized: false, transports: ['websocket'] }
which works with the existing lobby code.  We can add a new ioOptions param with this as the default.
