### ISSUE TITLE
Vue3 Support

### ISSUE THREAD

**Issue by davidtaddei** [westonsoftware/vue-webrtc#79]
Recently I have been working on a Vue 3 web interface using Quasar framework and came across this project. Unfortunately it seems specific to Vue 2 only (unless I am missing something, I am very new to this).

Support for Vue 3 would be amazing.

I have attempted porting the code into a Vue 3 project but it's like peeling an onion and am currently stuck on creating the SimpleSignalClient (not a constructor TypeError). If I am mistaken and this should work in Vue 3 I'd very much appreciate an assist.

Thanks!

**Comment by westonsoftware** [comment]
Thanks for voting for Vue 3, that is next on the project list.  Porting should be a matter of migrating to the new setup() syntax, I feel your pain here.  Quasar is awesome, I've often thought about creating a separate Quasar plugin for webrtc there.

**Comment by westonsoftware** [comment]
@davidtaddei  V3 has been released which now runs under Vue 3 ... give it a try and let us know how it works for you.
