### ISSUE TITLE
problem library - you only see yourself without the participation of your partner who also opened a camera

### ISSUE THREAD

**Issue by rimi1414** [westonsoftware/vue-webrtc#90]
Hi, there's a problem with the library.
I have been using it for a year and it worked great but suddenly a problem started-
 For some reason when you open the camera, you only see yourself without the participation of your partner who also opened a camera.

**Comment by westonsoftware** [comment]
Thanks for reporting this, I see the same thing, I restarted the server and I still see the problem.  Are you getting any error messages?  are you on v3.0.0?

**Comment by rimi1414** [comment]
Hey yeah, I wish you could solve it. I think the problem is with the
connection to one of the node.js directories you use (maybe something
else)? socket io or other of url .. Just guessing ... I wish it would be
resolved 🤞🤞

Tanks 🙏🙏
בתאריך יום א׳, 17 באפר׳ 2022 ב-16:27 מאת Andy Weston <
***@***.***>:

**Comment by westonsoftware** [comment]
I discovered that the number of web sockets is limited in the Azure tier that I'm using.  (You can run your own lobby server instead).  Also, I will expose the socket io opts param so that the http fallback is selectable for 3.0.1
--Andy

**Comment by rimi1414** [comment]
Okay thank you! If there is an opportunity to talk to you by email I would
be happy to help on the subject.

בתאריך יום ג׳, 19 באפר׳ 2022 ב-18:36 מאת Andy Weston <
***@***.***>:
