### ISSUE TITLE
Will the new version (after the fix) work in vue2 as well?

### ISSUE THREAD

**Issue by rimi1414** [westonsoftware/vue-webrtc#95]
Will the new version (after the fix) work in vue2 as well?

**Comment by westonsoftware** [comment]
No, you need to pull v2.0.0 from npm for Vue 2 from now on.

**Comment by rimi1414** [comment]
But for some reason in version 2.0 (which works in vue2
) Still have the problem that it is not possible to open a camera at both
ends, is there a way to solve this for this version as well?

thanks you!

‫בתאריך יום ה׳, 21 באפר׳ 2022 ב-20:41 מאת ‪Andy Weston‬‏ <‪
***@***.***‬‏>:‬
