### ISSUE TITLE
I wish you could help me with vue3 and thislibrary

### ISSUE THREAD

**Issue by rimi1414** [westonsoftware/vue-webrtc#97]
thanks for all.
I started a new project in Vue3 and than - installed vue-webrtc.
I tried to run but for some reason I get an error that I have been trying to fix for a week and do not know how.
 Maybe you know how to help?
This is the error:

ERROR in ./node_modules/vue-webrtc/dist/vue-webrtc.esm.js 7:0-42
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\rimir\WebstormProjects\tryingAgain\node_modules\vue-webrtc\dist'
@ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??

ERROR in ./node_modules/vue-webrtc/dist/vue-webrtc.esm.js 6:0-24
Module not found: Error: Can't resolve 'url' in 'C:\Users\rimir\WebstormProjects\tryingAgain\node_modules\vue-webrtc\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

thanks!!

**Comment by westonsoftware** [comment]
Try building the /sample project first ... then match those package settings in your new project.

**Comment by rimi1414** [comment]
I tried it but without success. Maybe there is a way to contact you for help? I just want to create a new vue3 project with this library. Thank you 🙏

**Comment by rockycastaneda** [comment]
Try running the sample first i got it up and running just fine.
1. Go to the sample folder on your command line then type npm install then hit enter
2. Type npm run serve then hit enter
3. Follow the link for Local or Network link after a successful compile

That should be it.
